name: Deploy to Umbler
on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Umbler
        uses: appleboy/ssh-action@master
        with:
          host: alderaan.ssh.umbler.com
          username: ssh-user
          port: 53999
          key: ${{ secrets.UMBLER_SSH_KEY }}
          script: |
            cd /home/defaultwebsite
            git pull origin main
